// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD1v7xCmMftmkKWMbfGuOiSDGoVPherg_0',
//     appId: '1:234826054071:android:ab29e370396feecf16d032',
//     messagingSenderId: '234826054071',
//     projectId: 'app-cop',
//     storageBucket: 'app-cop.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyADPtNu7jM7GIaumNJQB7LkDnIF89Ne_YA',
//     appId: '1:234826054071:ios:711cc13f9fe7c87616d032',
//     messagingSenderId: '234826054071',
//     projectId: 'app-cop',
//     storageBucket: 'app-cop.firebasestorage.app',
//     iosBundleId: 'com.aphrc.futuristic',
//   );
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAOVgQfaoIUyUX71n910EHXCugEUuaQGL0',
//     appId: '1:234826054071:web:cba7622490b9bc1816d032',
//     messagingSenderId: '234826054071',
//     projectId: 'app-cop',
//     authDomain: 'app-cop.firebaseapp.com',
//     storageBucket: 'app-cop.firebasestorage.app',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyADPtNu7jM7GIaumNJQB7LkDnIF89Ne_YA',
//     appId: '1:234826054071:ios:46f0a83366c711b816d032',
//     messagingSenderId: '234826054071',
//     projectId: 'app-cop',
//     storageBucket: 'app-cop.firebasestorage.app',
//     iosBundleId: 'com.example.projectf',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAOVgQfaoIUyUX71n910EHXCugEUuaQGL0',
//     appId: '1:234826054071:web:0e8714610f87dd4716d032',
//     messagingSenderId: '234826054071',
//     projectId: 'app-cop',
//     authDomain: 'app-cop.firebaseapp.com',
//     storageBucket: 'app-cop.firebasestorage.app',
//   );
//
// }